MBR_PARTITION_BOOT_INDICATOR_OFF       equ 0x00
MBR_PARTITION_START_CHS_OFF            equ 0x01
MBR_PARTITION_TYPE_OFF                 equ 0x04
MBR_PARTITION_END_CHS_OFF              equ 0x05
MBR_PARTITION_LBA_START_OFF            equ 0x08
MBR_PARTITION_TOTAL_SECTORS_OFF        equ 0x0C

FAT32_BPB_BYTES_PER_SECTOR_OFF        equ 0x00
FAT32_BPB_SECTORS_PER_CLUSTER_OFF     equ 0x02
FAT32_BPB_RESERVED_SECTORS_COUNT_OFF  equ 0x03
FAT32_BPB_NUMBER_FATS_OFF             equ 0x05
FAT32_BPB_ROOT_ENTRY_COUNT_OFF        equ 0x06
FAT32_BPB_TOTAL_SECTORS_16_OFF        equ 0x08
FAT32_BPB_MEDIA_DESCRIPTOR_OFF        equ 0x0A
FAT32_BPB_FAT_SIZE_16_OFF             equ 0x0B
FAT32_BPB_SECTORS_PER_TRACK_OFF       equ 0x0D
FAT32_BPB_NUMBER_OF_HEADS_OFF         equ 0x0F
FAT32_BPB_HIDDEN_SECTORS_OFF          equ 0x11
FAT32_BPB_TOTAL_SECTORS_32_OFF        equ 0x15

FAT32_EBPB_FAT_SIZE_32_OFF            equ 0x00
FAT32_EBPB_EXTENDED_FLAGS_OFF         equ 0x04
FAT32_EBPB_FS_VERSION_OFF             equ 0x06
FAT32_EBPB_ROOT_CLUSTER_OFF           equ 0x08
FAT32_EBPB_FS_INFO_SECTOR_OFF         equ 0x0C
FAT32_EBPB_BACKUP_BOOT_SECTOR_OFF     equ 0x0E
FAT32_EBPB_RESERVED1_OFF              equ 0x10
FAT32_EBPB_DRIVE_NUMBER_OFF           equ 0x1C
FAT32_EBPB_RESERVED2_OFF              equ 0x1D
FAT32_EBPB_BOOT_SIGNATURE_OFF         equ 0x1E
FAT32_EBPB_VOL_ID_OFF                 equ 0x1F
FAT32_EBPB_VOL_LABEL_OFF              equ 0x23
FAT32_EBPB_FS_TYPE_OFF                equ 0x2E

; FAT32 Directory Entry offsets
FAT32_DIR_NAME_OFF                  equ 0x00
FAT32_DIR_ATTRIBUTES_OFF            equ 0x0B
FAT32_DIR_NT_RESERVED_OFF           equ 0x0C
FAT32_DIR_CREATION_TIME_TENTHS_OFF  equ 0x0D
FAT32_DIR_CREATION_TIME_OFF         equ 0x0E
FAT32_DIR_CREATION_DATE_OFF         equ 0x10
FAT32_DIR_ACCESS_DATE_OFF           equ 0x12
FAT32_DIR_CLUSTER_HIGH_OFF          equ 0x14
FAT32_DIR_WRITE_TIME_OFF            equ 0x16
FAT32_DIR_WRITE_DATE_OFF            equ 0x18
FAT32_DIR_CLUSTER_LOW_OFF           equ 0x1A
FAT32_DIR_FILE_SIZE_OFF             equ 0x1C

FAT32_DIR_ENTRY_SIZE                equ 32

GDT_CODE_OFFSET                     equ 0x8
GDT_DATA_OFFSET                     equ 0x10

KERNEL_LOAD_ADDR                    equ 0x10000
KERNEL_LOAD_SEG                     equ 0x1000
KERNEL_LOAD_OFF                     equ 0x0000

STACK_ADDR                          equ 0x80000